### PR TITLE
remove ScalaCheck support

### PR DESCRIPTION
**Pull request by SethTisue**
in the Scala repo, we can get this directly through sbt instead

### CODE REVIEW

**Comment by SethTisue** [comment]
not to be merged until I've got a corresponding PR ready for scala/scala. I'm working on it

**Comment by SethTisue** [comment]
ok, i've tested this in the scala/scala repo using `publishLocal` on a snapshot, and it's good. I'm going to go ahead and merge so I can do the scala/scala PR.

(@szeiger, if you have any feedback on this, I'll respond promptly.)

**Comment by sjrd** [comment]
No we don't run that part. We only run `pos neg run`. Thanks for the notice, though.

**Comment by szeiger** [comment]
LGTM

**Pull request merged**
