### PR TITLE
Major cleanup without ant support

### PR DESCRIPTION
**Pull request by szeiger**
Now that the outlier ant is gone and we only have to deal with the already similar console and sbt runners, there is a lot of cruft we can remove. I have also cleaned up the configuration via system properties, which previously had special cases for sbt to support some properties there.

### CODE REVIEW

**Comment by szeiger** [comment]
Since nobody else wants to go that deep into the rather ugly partest codebase, I'll merge this without further review (as discussed at the team meeting in San Antonio).

**Comment by dwijnand** [comment]
note this was merged into a 2.12.0 branch

**Comment by SethTisue** [comment]
the "remove ant support" part happened again in f61dba1b12fc764f774b57a639f2630de63a9076

**Comment by SethTisue** [comment]
well, at least the ant removal part happened on mainline (by @lrytz), in f61dba1b12fc764f774b57a639f2630de63a9076

7cfb9e0 applied cleanly, so I submitted it as #108 

I tried but the other commits don't apply cleanly and would have to be carefully redone :-(

**Pull request merged**
