### PR TITLE
don't run mima

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
review by @szeiger

**Comment by szeiger** [comment]
Hm, what triggered MiMa in the first place? I don't see any command for it `admin/build.sh`.

**Comment by lrytz** [comment]
it's in the scala-module-plugin sbt plugin: https://github.com/scala/sbt-scala-modules/blob/master/src/main/scala/ScalaModulePlugin.scala#L113

**Comment by szeiger** [comment]
@lrytz I looked up when MiMa got enabled to ask the author why it was done in the first place. It turns out it was you in https://github.com/lrytz/scala-partest/commit/9bd6c574478c79820ddca26c38abef6115c57a6d. LGTM.

**Pull request merged**
