### PR TITLE
Add support "/* scalac: ... */" pragmas

### PR DESCRIPTION
**Pull request by dwijnand**
Aka backport scala/scala#6705, with a little scala/scala#7255 &
scala/scala#8808 thrown in.

Seeing as some things get cherry-picked back to 2.12.x and 2.12.x is branch-merged into 2.13.x, let's give 2.12.x this feature, for both backports and forward-merges.

cc @som-snytt @hrhino

### CODE REVIEW

**Comment by som-snytt** [comment]
Probably more progress is missing. But hrhino does so much work on 2.12 that it would be nice to realize the benefit. The alternative is to port all the 2.12 tests to Vulpix.

**Comment by dwijnand** [comment]
I don't want to spend too much time on this.  In my eyes it's fine for partest in 2.13 to continue improving, and it's fine that 2.12 doesn't have all those improvements.  This is just above cherry-picking the flags difference as 2.12 and 2.13 are now incompatible with one another.  Did you have specific changes in mind that need to be back-ported?

**Comment by som-snytt** [comment]
When I looked yesterday, I was like oh I think I made a couple of other changes. But I was also undermotivated to research it. ATM, I'm beginning my paid work. Wait, if it's Monday, why does it feel like Wednesday? My Vulpix joke (I forgot to explain it's the dotty test) was the best I could do in the moment to express myself.

**Comment by dwijnand** [comment]
Yeah, I spent a bit of time of time blame various files in various branches/repos.  But rather than reconstruct history, I'm just going to get CI passing before I run out of time budget on this one.

**Comment by dwijnand** [comment]
https://github.com/scala/scala/pull/9169 instead

**Pull request closed without merging**
