### PR TITLE
Improvements for the Scala SBT build

### PR DESCRIPTION
**Pull request by retronym**
Review by @szeiger or @SethTisue

### CODE REVIEW

**Comment by retronym** [comment]
The second commit intends to fix https://github.com/scala/scala-partest-interface/issues/14

**Comment by retronym** [comment]
I've tested this out locally:

```
> show test/it:dependencyClasspath
[info] Packaging /Users/jason/code/scala2/build-sbt/pack/lib/scala-partest-javaagent.jar ...
[info] Done packaging.
[info] List(Attributed(/Users/jason/code/scala2/build-sbt/quick/classes/test), Attributed(/Users/jason/code/scala2/build-sbt/quick/classes/compiler), Attributed(/Users/jason/code/scala2/build-sbt/quick/classes/library), Attributed(/Users/jason/code/scala2/build-sbt/libs/classes/forkjoin), Attributed(/Users/jason/code/scala2/build-sbt/quick/classes/reflect), Attributed(/Users/jason/code/scala2/build-sbt/quick/classes/interactive), Attributed(/Users/jason/code/scala2/build-sbt/quick/classes/actors), Attributed(/Users/jason/code/scala2/build-sbt/quick/classes/repl-jline-embedded), Attributed(/Users/jason/code/scala2/build-sbt/quick/classes/repl-jline), Attributed(/Users/jason/code/scala2/build-sbt/quick/classes/repl), Attributed(/Users/jason/code/scala2/build-sbt/quick/classes/scalap), Attributed(/Users/jason/code/scala2/build-sbt/quick/classes/partest-extras), Attributed(/Users/jason/code/scala2/build-sbt/pack/lib/scala-partest-javaagent.jar), Attributed(/Users/jason/code/scala2/build-sbt/quick/classes/scaladoc), Attributed(/Users/jason/code/scala2/test/files/lib/annotations.jar), Attributed(/Users/jason/code/scala2/test/files/lib/enums.jar), Attributed(/Users/jason/code/scala2/test/files/lib/genericNest.jar), Attributed(/Users/jason/code/scala2/test/files/lib/jsoup-1.3.1.jar), Attributed(/Users/jason/code/scala2/test/files/lib/macro210.jar), Attributed(/Users/jason/code/scala2/test/files/lib/methvsfield.jar), Attributed(/Users/jason/code/scala2/test/files/lib/nest.jar), Attributed(/Users/jason/code/scala2/test/lib), Attributed(/Users/jason/.ivy2/cache/org.apache.ant/ant/jars/ant-1.9.4.jar), Attributed(/Users/jason/.ivy2/cache/org.apache.ant/ant-launcher/jars/ant-launcher-1.9.4.jar), Attributed(/Users/jason/.ivy2/cache/org.scala-lang.modules/scala-asm/bundles/scala-asm-5.0.4-scala-3.jar), Attributed(/Users/jason/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.4.jar), Attributed(/Users/jason/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.4.jar), Attributed(/Users/jason/.ivy2/cache/jline/jline/jars/jline-2.12.1.jar), Attributed(/Users/jason/.ivy2/local/org.scala-lang.modules/scala-partest_2.11/1.0.12-SNAPSHOT/jars/scala-partest_2.11.jar), Attributed(/Users/jason/.ivy2/cache/com.googlecode.java-diff-utils/diffutils/jars/diffutils-1.3.0.jar), Attributed(/Users/jason/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar), Attributed(/Users/jason/.ivy2/cache/org.scala-lang.modules/scala-partest-interface_2.11/jars/scala-partest-interface_2.11-0.7.0.jar), Attributed(/Users/jason/.ivy2/cache/org.scalacheck/scalacheck_2.11/jars/scalacheck_2.11-1.11.6.jar))
[success] Total time: 1 s, completed 06/02/2016 9:57:50 PM
> partest --srcpath pending --run
[info] Packaging /Users/jason/code/scala2/build-sbt/pack/lib/scala-partest-javaagent.jar ...
[info] Done packaging.
Partest version:
Compiler under test: $baseDir/compiler
Scala version is:    Scala compiler version 2.11.8-20160205-124626-b51fe3d -- Copyright 2002-2016, LAMP/EPFL
Scalac options are:
Compilation Path:    /Users/jason/code/scala2/target/test/it-classes:$baseDir/test:$baseDir/compiler:$baseDir/library:/Users/jason/code/scala2/build-sbt/libs/classes/forkjoin:$baseDir/reflect:$baseDir/interactive:$baseDir/actors:$baseDir/repl-jline-embedded:$baseDir/repl-jline:$baseDir/repl:$baseDir/scalap:$baseDir/partest-extras:/Users/jason/code/scala2/build-sbt/pack/lib/scala-partest-javaagent.jar:$baseDir/scaladoc:/Users/jason/code/scala2/test/files/lib/annotations.jar:/Users/jason/code/scala2/test/files/lib/enums.jar:/Users/jason/code/scala2/test/files/lib/genericNest.jar:/Users/jason/code/scala2/test/files/lib/jsoup-1.3.1.jar:/Users/jason/code/scala2/test/files/lib/macro210.jar:/Users/jason/code/scala2/test/files/lib/methvsfield.jar:/Users/jason/code/scala2/test/files/lib/nest.jar:/Users/jason/code/scala2/test/lib:/Users/jason/.ivy2/cache/org.apache.ant/ant/jars/ant-1.9.4.jar:/Users/jason/.ivy2/cache/org.apache.ant/ant-launcher/jars/ant-launcher-1.9.4.jar:/Users/jason/.ivy2/cache/org.scala-lang.modules/scala-asm/bundles/scala-asm-5.0.4-scala-3.jar:/Users/jason/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.4.jar:/Users/jason/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.4.jar:/Users/jason/.ivy2/cache/jline/jline/jars/jline-2.12.1.jar:/Users/jason/.ivy2/local/org.scala-lang.modules/scala-partest_2.11/1.0.12-SNAPSHOT/jars/scala-partest_2.11.jar:/Users/jason/.ivy2/cache/com.googlecode.java-diff-utils/diffutils/jars/diffutils-1.3.0.jar:/Users/jason/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar:/Users/jason/.ivy2/cache/org.scala-lang.modules/scala-partest-interface_2.11/jars/scala-partest-interface_2.11-0.7.0.jar:/Users/jason/.ivy2/cache/org.scalacheck/scalacheck_2.11/jars/scalacheck_2.11-1.11.6.jar:/Users/jason/.sbt/boot/scala-2.10.5/org.scala-sbt/sbt/0.13.9/test-agent-0.13.9.jar:/Users/jason/.sbt/boot/scala-2.10.5/org.scala-sbt/sbt/0.13.9/test-interface-1.0.jar
Java binaries in:    /Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre/bin
Java runtime is:     Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)
Java options are:    -Xmx1024M -Xms64M -XX:MaxPermSize=128M
baseDir:             /Users/jason/code/scala2/build-sbt/quick/classes
sourceDir:           /Users/jason/code/scala2/test/pending

Selected 98 tests drawn from 1 named test categories

# starting 98 tests in run
!!  1 - run/idempotency-partial-functions.scala   [compilation failed]
!!  2 - run/jar-version.scala                     [compilation failed]
!!  3 - run/macro-expand-default                  [compilation failed]
!!  4 - run/hk-lub-fail.scala                     [compilation failed]
!!  5 - run/macro-expand-implicit-macro-defeats-type-inference  [compilation failed]
!!  6 - run/instanceOfAndTypeMatching.scala       [compilation failed]
!!  7 - run/bug4704run.scala                      [compilation failed]
!!  8 - run/macro-expand-macro-has-context-bound  [compilation failed]
!!  9 - run/macro-expand-named                    [compilation failed]
!! 10 - run/macro-expand-tparams-prefix-e1        [compilation failed]
^C
[warn] Canceling execution...
Exception in thread "Thread-70" java.io.EOFException
```

To automate running the scaladoc tests, I think we'll need to create another config (alongside `IntegrationTest`) in our SBT build that adds the test framework option `--srcpath scaladoc`.

**Comment by szeiger** [comment]
LGTM. Honoring `--srcpath` makes sense because we already allow arbitrary partest options to be passed from sbt.

For a proper integration of the scaladoc tests we should reconsider SBTRunner's `srcDir` parameter and either use that to pass the correct dir from partest-interface by default (users could still override it with `--srcpath`) or drop it and always use `--srcpath`.

We may want to change the project/config scoping for tests in the sbt build as well. Adding configs is a bit ugly, so I'd rather go for a separate project. Do we even need to use the `it` config for partest? It's not fundamentally different from the junit tests. We could have three subprojects for junit tests, standard partest tests and scaladoc partet tests, each scoped to the `test` configuration.

**Comment by retronym** [comment]
> For a proper integration of the scaladoc tests we should reconsider SBTRunner's srcDir parameter and either use that to pass the correct dir from partest-interface by default (users could still override it with --srcpath) or drop it and always use --srcpath.

That would be the principled approach, but in the meantime we just need our CI to call `partest --srcdir scaladoc` in addition to the other test commands.

> We could have three subprojects for junit tests, standard partest tests and scaladoc partet tests, each scoped to the test configuration.

That sounds like a good idea.

**Pull request merged**
