### PR TITLE
Remove `--self-test` (not used)

### PR DESCRIPTION
**Pull request by SethTisue**
cherry-picked from https://github.com/scala/scala-partest/pull/68
which never made it onto a mainline branch

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
LGTM.

Future cleanups could go down the `TestKinds.testsForPartest` code path and prune.

**Comment by SethTisue** [comment]
( note that 1.2.x is our new 2.13-only branch)

**Comment by SethTisue** [comment]
ah nice catch, added another commit removing a bit more code.

**Comment by SethTisue** [comment]
silly me, I got wrapped up in this and forgot about https://github.com/scala/scala/pull/6566. I'll re- check on this after that lands

**Comment by SethTisue** [comment]
why wait. I have added this to https://github.com/scala/scala/pull/6566 as an additional commit

**Pull request closed without merging**
