### PR TITLE
Updated SBTRunner improvements for passing arguments to partest

### PR DESCRIPTION
**Pull request by szeiger**
This is an updated version of #24 to be used together with https://github.com/scala/scala-partest-interface/pull/5.

- Rebased on top of master
- Removed dependency version upgrades (just use what we have in master now)
- Changed the new makeStatus method to benefit from exhaustiveness checking

### CODE REVIEW

**Comment by szeiger** [comment]
I'm not sure what to make of the build status. The previous build failed because of MiMa but the new commit doesn't affect binary compatibility and the build passed. If this needs to be binary compatible, more work is required. I have a patch for the Scala build ready that passes 100% of partest in the sbt build. It depends on this new version of partest (and the corresponding update for scala-partest-interface).

**Comment by szeiger** [comment]
@adriaanm, do you want to review this or assign someone else?

**Comment by adriaanm** [comment]
@lrytz, could you take a look, bitte?

**Comment by lrytz** [comment]
bien sûr

**Comment by lrytz** [comment]
LGTM!

**Comment by SethTisue** [comment]
@szeiger if you need help publishing a new version of scala-partest so that you can depend on it from scala/scala, I'm available. there's a slow path and a fast path.

the slow path involves publishing to a staging repo only, adding the dependency to scala/scala pointing to the staging repo, verifying that the tests pass, and only then going back and doing the module release for real.

the fast path is just, just publish the module and figure YOLO and if you end up having to publish another one after that, oh well.

I went through the slow path once on scala-xml, but scala-xml is a project that lots of people use, so there was some value in making sure we didn't put out a release that needed to immediately be replaced. but only a few projects (scala, scala-js, dotty) depend on partest, so perhaps the fast path is fine here — you might see what the rest of the team thinks.

**Comment by lrytz** [comment]
I agree YOLO is just fine for partest. For other modules, I'd say it depends on the size / riskiness of the patch.

**Pull request merged**
