### PR TITLE
Script to publish manually (without travis)

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @SethTisue. Feel free to try it out and publish a release, it will only stage it on sonatype, and you can just drop the staging repository.

**Comment by lrytz** [comment]
build failed due to a travis issue: https://github.com/travis-ci/travis-ci/issues/4527 / https://twitter.com/travisci/status/621055235038035968

**Comment by SethTisue** [comment]
sweet use of unicode

**Comment by SethTisue** [comment]
it works. thanks!

about actually merging it though, what do you think about putting it in https://github.com/adriaanm/binfu instead, so we have one copy of it that can be used on any of the modules (partest, xml, etc)

**Comment by lrytz** [comment]
it would be good to avoid manually maintaining same files across all the modules repo, also for the rest in `admin/`. i think we should set up some scripting for that.

not sure about putting the files somewhere else though. our module maintainers are most likely not using binfu.

**Comment by SethTisue** [comment]
@szeiger this got left undecided, maybe see what you think?

**Comment by szeiger** [comment]
Have you considered putting it into scala-dist?

**Comment by SethTisue** [comment]
right now scala-dist has exactly one job — better to keep it that way I think

**Comment by szeiger** [comment]
I'll merge it. We can always decide to put it into a better location later.

**Comment by lrytz** [comment]
wohoo! my emoji-script!

**Pull request merged**
