### PR TITLE
Remove ant support

### PR DESCRIPTION
**Pull request by lrytz**
Now that https://github.com/scala/scala/pull/6255 is merged

### CODE REVIEW

**Comment by lrytz** [comment]
Let's try to move this ahead quickly so that we can unblock the travis build for 2.13.x

**Comment by SethTisue** [comment]
```diff
-There are three ways of invoking partest:
+Partest is invoked from sbt.
```

❤️

**Comment by dwijnand** [comment]
Just merge conflicted yourself with #101 🏥

**Comment by lrytz** [comment]
I know :)

**Review by SethTisue — APPROVED** [review]
LGTM if Travis-CI likes it

**Pull request merged**
